import React from "react";
import { Card, Col, Icon, Row } from "antd";
import styled from "styled-components";
import BigContainer from "./BigContainer";
import { LocaleMessage } from "../../internationalization/components";
import lang from "../../internationalization/LocaleStore/lang";

const MyIcon = Icon.createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_838122_vx82b0yre5.js", // generated by iconfont.cn
});

function Iconfont(props: { type: string }) {
  return <MyIcon type={props.type} style={{marginRight: "8px"}}/>;
}

interface Feature {
  icon: string;
  title: string;
  description: string;
}

// Features data is now loaded from internationalization

function CardFeature(props: { feature: Feature }) {
  const {icon, title, description} = props.feature;
  return <Card title={<span><Iconfont type={icon}/>{title}</span>}
               style={{height: "220px"}}
  >
    {/*<h4>{x.title}</h4>*/}
    <span>{description}</span>
  </Card>;
}

const FeatureContainer = styled.div`
  height: 280px;
  padding: 20px 16px;
  display: flex;
  flex-direction: column;
  background: #ffffff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
  
  &:hover {
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
    transform: translateY(-2px);
  }
  
  svg {
    width: 52px;
    height: 52px;
    margin-bottom: 8px;
  }
  
  h3 {
    padding: 8px 4px;
    height: 70px;
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    font-family: "Times New Roman", Times, serif !important;
    font-size: 16px;
    font-weight: 600;
    line-height: 1.3;
    margin-bottom: 12px;
  }
  
  small {
    flex: 1;
    display: flex;
    align-items: flex-start;
    text-align: center;
    line-height: 1.5;
    font-family: "Times New Roman", Times, serif !important;
    font-size: 14px;
    color: #666;
  }
`;

function StandardFeature(props: { feature: Feature }) {
  const {icon, title, description} = props.feature;
  return <FeatureContainer>
    <div style={{textAlign: "center"}}>
      <MyIcon type={icon}/>
      <h3>{title}</h3>
      {/*<div style={{ textAlign: "left" }}>*/}
        <small>{description}</small>
      {/*</div>*/}
    </div>
  </FeatureContainer>;
}

interface Props {

}

const featureIcons = [
  "icon-Artboard",
  "icon-fengxian3", 
  "icon-rengongzhineng",
  "icon-api",
  "icon-juleimoban",
  "icon-moxing1",
  "icon-zhengcejiedu",
  "icon-yuanyou2"
];

export default function Features(props: Props) {
  const featuresEn = [
    {
      title: "Multi-level Asset Allocation",
      description: "Based on the classic Markowitz model with dual risk-return approach. Optimizes for market characteristics with careful target consideration and meticulous recommendations."
    },
    {
      title: "Quantitative Timing-Based Risk Control",
      description: "Monitors quality stocks using short-term timing models. Filters noise through Hilbert and Fourier transforms to capture return inflection points."
    },
    {
      title: "Machine Learning for Prediction (LSTM)",
      description: "Utilizes cutting-edge LSTM neural networks for deep learning. Provides more accurate stock option trend predictions than traditional models."
    },
    {
      title: "Data Mining Based on Citi API",
      description: "Discovers valuable data from users' Citibank API. Generates optimized variables and indicators that reflect user risk-return preferences."
    },
    {
      title: "Intelligent Recommendations Based on Clustering",
      description: "Clusters users with similar risk preferences using Kmeans++ algorithm. LOF removes outliers while self-adjusting centers improve accuracy."
    },
    {
      title: "Application of DCC-MIDAS Model",
      description: "Estimates dynamic correlation between crude oil futures and spot markets. GARCH volatility components improve estimation effectiveness."
    },
    {
      title: "Economic Policy Uncertainty (EPU) Factor",
      description: "Quantifies policy impact on A-shares and commodity markets using uncertainty index for precise trend predictions."
    },
    {
      title: "INE Crude Oil Futures",
      description: "RMB-priced futures targeting Asian markets with medium sour crude oil, representing 45% of global production."
    }
  ];

  return <div style={{paddingTop: "40px", paddingBottom: "80px", backgroundColor: "#f8f9fa"}}>
  <BigContainer title="System Features">
    <Row style={{maxWidth: "1200px", marginLeft: "auto", marginRight: "auto"}} gutter={[24, 32]}>
      {featuresEn.map((feature, i) => (
        <Col xs={24} sm={12} md={12} lg={6} key={i}>
          <StandardFeature feature={{
            icon: featureIcons[i],
            title: feature.title,
            description: feature.description
          }}/>
        </Col>
      ))
      }
    </Row>
  </BigContainer></div>;
}
